### ISSUE TITLE
TSM Feature extraction

### ISSUE THREAD

**Issue by Camillo4eyes** [assembly-101/assembly101-action-recognition#6]
HI! I've trained TSM with a subset of the videos and I'm trying to extract features to have features similar to what you provide. Some advice?

**Comment by assembly-101** [comment]
Hi Camillo,

You may find some information in this [issue](https://github.com/assembly-101/assembly101-action-recognition/issues/1).
We modify the [RU-LSTM](https://github.com/fpv-iplab/rulstm/blob/master/FEATEXT/extract_example_rgb.py) code for feature extraction by replacing the TSN with a TSM.

Please let us know if you face any issues.

**Comment by Camillo4eyes** [comment]
Using your pretrained model [(link)](https://drive.google.com/file/d/11uFkqg1tWfWeATukjFL_HXHB6Gs1iGfU/view), I am unable to obtain the same extracted features as yours. I want to obtain the features that you have extracted in order to validate the code and use it to extract features using my trained model. Any suggestions?

**Comment by assembly-101** [comment]
Hi Camillo,

Can you explain what do you mean by "unable to obtain the same extracted features" i.e. how do you measure it? Are you comparing with some of our benchmarks?

**Note**: This pretrained [TSM model](https://drive.google.com/file/d/11uFkqg1tWfWeATukjFL_HXHB6Gs1iGfU/view) has been trained on fixed+ego (all 12 views).

**Comment by Camillo4eyes** [comment]
I have downloaded the TSM features provided by you, and I want to obtain the same features (using your pretrained model) to ensure that the extraction code is correct. Then, I will proceed with the extraction using the model trained by myself.

**Comment by dibschat** [comment]
Hi Camillo,

If I understood correctly, are you using your custom per-frame feature extraction code using our pretrained (on all 12 views) TSM and then comparing with the per-frame features provided by us in the drive?

What metric are you using to calculate the feature similarity? (e.g. L2, L1?) Note that the features might will not be exact and will depend on the input transform you are using and the best way to check is to run any [segmentation baselines](https://github.com/assembly-101/assembly101-temporal-action-segmentation) with your features and see if you can reproduce the results.

Instead of using the [RU-LSTM](https://github.com/fpv-iplab/rulstm/blob/master/FEATEXT/extract_example_rgb.py#L27) transforms, please use the image transforms provided in [test_models.py](https://github.com/assembly-101/assembly101-action-recognition/blob/main/TSM-action-recognition/test_models.py#L155) as follows:
```python
transform = torchvision.transforms.Compose([
            GroupScale(net.scale_size),
            GroupCenterCrop(input_size),
            Stack(roll=(this_arch in ['BNInception', 'InceptionV3'])),
            ToTorchFormatTensor(div=(this_arch not in ['BNInception', 'InceptionV3'])),
            GroupNormalize(net.input_mean, net.input_std),
        ])
```

Let me know if this works !
